adiciona links com implementações em python
italojs/awesome-machine-learning-portugues pull request #2
Opened 2018-12-28 14:04 UTC by arnaldog12

- implementação de Árvores de Decisão, kNN, Regressão Linear/Multilinear/Polinomial
- fix typos

2018-12-28 19:28 UTC, italojs requested changes

2018-12-28 19:28 UTC, italojs commented on README.MD
> +## Adaboost
Vlw pelas contribuições!
Mas uma dúvida, eu ainda não vi como funciona o Adaboost, você acha que ele é mais fácil que o KNN?
pergunto isso pois os tópicos estão em ordem estudos.

2018-12-28 19:29 UTC, italojs commented
cara, eu procurei esse 'typo' que as pessoas falaram e não encontrei, nem por busca (ctrl+f) haha

2018-12-29 10:27 UTC, arnaldog12 commented on README.MD
> +## Adaboost
Realmente não é. Vou ajeitar a ordem, então. Sendo assim, Regressão Linear deveria ser um dos primeiros também, não acha?

2018-12-29 10:29 UTC, arnaldog12 commented
> cara, eu procurei esse 'typo' que as pessoas falaram e não encontrei, nem por busca (ctrl+f) haha

_typo_ significa "erro de digitação" em inglês, como em *Machine learning __superviosionado__*.

2018-12-29 10:41 UTC, arnaldog12 commented on README.MD
> +## Adaboost
e SVM deveria ser um dos últimos também, não? Talvez antes dos assuntos relacionados a Redes Neurais.

2018-12-29 11:52 UTC, italojs commented on README.MD
> +## Adaboost
eu acho mais fácil SVM do que redes neurais, mas é uma opnião bem pessoal, e quanto a regressão, eu acho legal o KNN ou naive bayes como primeiro algoritmo pra não assustar aqueles que não vieram do meio matemático ou tem um receio quanto ao meta, para que eles tenham seu primeiro contato com a "matemática codificada", eu acho muito mais fácil entender uma distancia euclidiana ou uma probabilidade do que uma regressão, concorda?

2018-12-30 12:24 UTC, merged